---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tbtc-dapp-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.allow-http: "false"
spec:
  tls:
  - secretName: dapp-dev-tbtc-network
  backend:
    serviceName: tbtc-dapp
    servicePort: 80
