version: 2.1

executors:
  docker-node:
    docker:
      - image: circleci/node:11
  docker-thesis-buildpack:
    docker:
      - image: thesisco/docker-buildpack:bionic

orbs:
  gcp-gcr: circleci/gcp-gcr@0.0.4

jobs:
  resolve_latest:
    executor: docker-node
    steps:
      - checkout
      - run:
          name: Resolve latest tbtc.js
          command: |
            npm update @keep-network/tbtc.js
      - persist_to_workspace:
          root: .
          paths:
            - package.json
            - package-lock.json
  build_dapp:
    executor: docker-thesis-buildpack
    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Set Gcloud Auth
          command: |
            echo $GCLOUD_SERVICE_KEY_GET_BUCKET_OBJECT > ~/gcloud-service-key.json
            gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
      - run:
          name: Run Docker build
          command: |
            docker build -t build --target build .
            docker build -t $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/tbtc-dapp .
      - run:
          name: Save tbtc-dapp image
          command: |
            mkdir -p /tmp/tbtc-dapp/docker-images/
            docker save -o /tmp/tbtc-dapp/docker-images/tbtc-dapp.tar $GCR_REGISTRY_URL/$GOOGLE_PROJECT_ID/tbtc-dapp
      - persist_to_workspace:
          root: /tmp/tbtc-dapp
          paths:
            - docker-images

  publish_dapp:
    executor: gcp-gcr/default
    steps:
      - attach_workspace:
          at: /tmp/tbtc-dapp
      - run:
          name: Load tbtc-dapp image
          command: |
            docker load -i /tmp/tbtc-dapp/docker-images/tbtc-dapp.tar
      - gcp-gcr/gcr-auth:
          google-project-id: GOOGLE_PROJECT_ID
          google-compute-zone: GOOGLE_COMPUTE_ZONE_A
          # This param doesn't actually set anything, leaving here as a reminder to check when they fix it.
          gcloud-service-key: GCLOUD_SERVICE_KEY
      - gcp-gcr/push-image:
          google-project-id: GOOGLE_PROJECT_ID
          registry-url: $GCR_REGISTRY_URL
          image: tbtc-dapp
          tag: latest

workflows:
  version: 2
  dapp_keep_dev:
    jobs:
      - resolve_latest:
          context: keep-dev
      - build_dapp:
          context: keep-dev
          requires:
            - resolve_latest
      - publish_dapp:
          filters:
            branches:
              only: master
          context: keep-dev
          requires:
            - build_dapp
  dapp_keep_test:
    jobs:
      - keep_test_approval:
          type: approval
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/ropsten\/.*/
      - resolve_latest:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/ropsten\/.*/
          context: keep-test
          requires:
            - keep_test_approval
      - build_dapp:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/ropsten\/.*/
          context: keep-test
          requires:
            - resolve_latest
      - publish_dapp:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /releases\/ropsten\/.*/
          context: keep-test
          requires:
            - build_dapp
